#pragma config(CircuitBoardType, typeCktBoardDuemilanove)
#pragma config(Sensor, dgtl8,  MPOSL,          sensorDigitalIn)
#pragma config(Sensor, dgtl9,  MPOSR,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, M0,             sensorDigitalOut)
#pragma config(Sensor, dgtl11, M1,             sensorDigitalOut)
#pragma config(Sensor, dgtl12, M2,             sensorDigitalOut)
#pragma config(Sensor, dgtl13, M3,             sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*******************************************************************************

Program to interface MPOS and design Line following Robot

********************************************************************************

Microcontroller: ATmega-328P
clock: 16Mhz
compiler: RobotC
********************************************************************************

M0-Digital10
M1-Digital11
M2-Digital12
M3-Digital13
MPOSL-digital8
MPOSR-digital9
*********************************************************************************/

// MOTOR CONNECTIONS
//    R       L
//  +   -    -  +

task main()
{
  while(true)
  {
   if(SensorValue[MPOSL]==true)		    // When Left sensor comes on Black line its value goes to '1'
   {
     		//left turn
				SensorValue[M0] = true;
  			SensorValue[M1] = false;
  			SensorValue[M2] = false;
  			SensorValue[M3] = false;
  			wait1Msec(300);
   }
   else if(SensorValue[MPOSR]==true)	//right Sensor sensor comes on Black line its value goes to '1'
   {
     		//Right Turn
				SensorValue[M0] = false;
  			SensorValue[M1] = false;
  			SensorValue[M2] = true;
  			SensorValue[M3] = false;
     		wait1Msec(300);
   }
   else
   {
        //Forward
       	SensorValue[M0] = true;
  			SensorValue[M1] = false;
  			SensorValue[M2] = true;
  			SensorValue[M3] = false;
   }
  }
}
